spring:
  # DataSource Config
  datasource:
    write:
      url: jdbc:oracle:thin:@192.168.1.231:1521:PlAtFoRm
      username: platform
      password: platform
      driver-class-name: oracle.jdbc.driver.OracleDriver
      max-active: 20
      initial-size: 1
      min-idle: 3
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x' FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,log4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=3000
      remove-abandoned: true
      remove-abandoned-timeout: 60
      # 合并多个DruidDataSource的监控数据
      #spring.datasource.useGlobalDataSourceStat=true
    read:
      url: jdbc:oracle:thin:@192.168.1.231:1521:PlAtFoRm
      username: platform
      password: platform
      driver-class-name: oracle.jdbc.driver.OracleDriver
      max-active: 20
      initial-size: 1
      min-idle: 3
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x' FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,log4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=3000
      remove-abandoned: true
      remove-abandoned-timeout: 60
      # 合并多个DruidDataSource的监控数据
      #spring.datasource.useGlobalDataSourceStat=true
  redis:
    database: 2
    host: 127.0.0.1
    password: 123456 # Login password of the redis server.
    port: 6379
    timeout: 0
    pool:
      max-active: 8 #最大连接数
      max-idle: 8 #最大空闲连接数
      max-wait: -1 #最大等待时间
      min-idle: 0 #初始化连接数

  http:
      multipart:
        enabled: true # 默认支持文件上传
        file-size-threshold: 4KB #支持文件写入磁盘
        location:  D:/apache-tomcat-7.0.65-myeclipse2014_3/webapps/data/tmp # 上传文件的临时目录
        max-file-size: 50Mb # 最大支持文件大小
        max-request-size: 50Mb # 最大支持请求大小

  rabbitmq:
    host: 192.168.6.120
    port: 5672
    username: admin
    password: 123456
    virtualHost: /

server:
  port: 8085
  tomcat:
      remote-ip-header: x-forwarded-for
      protocol-header: x-forwarded-proto
      port-header: X-Forwarded-Port
      accesslog:
        debug: true #请求响应数据调试
  use-forward-headers: true


security:
  jwt:
    secret: k09BQnaF
    expiration: 604800 #1小时过期时间

fileUpload:
  zyportalclient:
    url: D:/apache-tomcat-7.0.65-myeclipse2014_3/webapps/data/files

upload:
    #Disk upload
    work-folder-name: D:/apache-tomcat-7.0.65-myeclipse2014_3/webapps/data/files #文件存储路径
    access-url: http://127.0.0.1:8090 #文件访问地址，可使用反向代理

dumu:
   face: D:/apache-tomcat-7.0.65-myeclipse2014_3/webapps/dumu/face #人脸库图片
   black:  D:/apache-tomcat-7.0.65-myeclipse2014_3/webapps/dumu/black #黑名单
   white:   D:/apache-tomcat-7.0.65-myeclipse2014_3/webapps/dumu/white #白名单
   vip: D:/apache-tomcat-7.0.65-myeclipse2014_3/webapps/dumu/vip #vip名单
   other: D:/apache-tomcat-7.0.65-myeclipse2014_3/webapps/dumu/other #vip名单
   stranger: D:/apache-tomcat-7.0.65-myeclipse2014_3/webapps/dumu/stranger #陌生人名单


#日志输出配置
logback:
  log_home: d:/logs/


wx-server: http://192.168.6.142:18083

warnpush:
    led: ${wx-server}/device/led/sendTextWithNoAuth
    ledopen: 0
    gb: ${wx-server}/device/broadcast/sendTextWithNoAuth
    gbopen: 0